path: /Users/johnomole/Desktop/pacaba/datasets # dataset root dir--   Please change it to your root directory
train: ParkingCarsDataset/yolo/train/
val: ParkingCarsDataset/yolo/val
test: ParkingCarsDataset/yolo/test

# Classes
names:
  0: vehicle
